### ISSUE TITLE
Could not find assembly file.

### ISSUE THREAD

**Issue by scyto** [QModManager/QModManager#62] opened 2019-03-01 03:10 UTC
I get following issue:

```
Could not find the assembly file.
Please make sure you have installed QModManager in the right folder.
If the problem persists, open a bug report on NexusMods or an issue on GitHub

Press any key to exit...
```

appears to be installed in the correct place? it auto detected and the dir contains a binch of DLLs and unity files (D:\Games\Steam\steamapps\common\Subnautica\Subnautica_Data\Managed)

any ideas?

**Comment by scyto** [comment] 2019-03-01 03:16
hmm despite this error the mod is loaded after running the app, go figure, you can close unless you want more info?

**Comment by kylinator25** [comment] 2019-03-01 03:19
You need to install QMods to Subnautica, not the managed folder

**Comment by scyto** [comment] 2019-03-01 03:21
> You need to install QMods to Subnautica, not the managed folder

I did install it to the subnautica folder via the installer, the installer put the EXE in that folder.

**Comment by kylinator25** [comment] 2019-03-01 03:22
Where is your QModInstaller.dll located? (this is created by the installer)

**Comment by scyto** [comment] 2019-03-01 03:26
> Where is your QModInstaller.dll located? (this is created by the installer)

As I said "D:\Games\Steam\steamapps\common\Subnautica\Subnautica_Data\Managed" this is where the installer installed it.  

The UI in the installer auto detected and showed the install path of the detected game as D:\Games\Steam\steamapps\common\Subnautica

**Comment by scyto** [comment] 2019-03-01 03:28
@kylinator25 if you look at the ISS source you will see that this is right location, I am not some dumb noob you know. I have hand crafted MSIs from scratch. https://github.com/QModManager/QModManager/blob/master/Installer/QModsInstallerScript.iss

**Comment by kylinator25** [comment] 2019-03-01 03:37
Well if the mod is working just fine, why bother posting?

**Comment by scyto** [comment] 2019-03-01 03:40
> Well if the mod is working just fine, why bother posting?

because when I posted I didn't know it wasn't working, and why I immediately posted straight away it was now working and saying issue could be closed unless the code owners (which you are not one of) wants the info. Is that ok with you your highness? 'sir post the non-helpful suggestions and not read carefully lord of github'?

**Comment by kylinator25** [comment] 2019-03-01 03:43
oh rip, sorry about that, didnt see the message lmao

**Comment by AlexejheroYTB** [comment] 2019-03-01 04:59
I'm going to take a look at this. This could be confusing for a lot of people

**Comment by scyto** [comment] 2019-03-01 05:29
> I'm going to take a look at this. This could be confusing for a lot of people

Thanks, FYI I was running experimental branch of subnautica and latest windows 10 fast ring insider build, if that matters.

**Comment by AlexejheroYTB** [comment] 2019-03-01 05:34
QModManager is not compatible with experimental, but to be fair, it doesn't say it anywhere. I will put up a bright neon sign on the nexus page.
Nevertheless, this is not the cause of the error. It has to do with something else. I am reopening this until we find a fix

**Comment by AlexejheroYTB** [comment] 2019-05-16 17:28
Fixed in the next update

**Closed by AlexejheroYTB** 2019-05-16 17:28 UTC
Labels: Type: Bug
